language: csharp
mono: latest
dotnet: 2.1.3
dist: trusty
sudo: false
solution: AltCover.sln

git:
  depth: false

# if: (NOT branch =~ ^develop/.*$) AND tag IS blank
if: (branch = develop/travis) AND (tag IS blank)

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

install:
  - nuget restore ./AltCover.sln

script:
  - mono packages/FAKE.4.64.3/tools/FAKE.exe Build/prebuild.fsx
  - mono packages/FAKE.4.64.3/tools/FAKE.exe Build/build.fsx

