version: 1.4.{build}-beta
branches:
  except:
  - /develop.*/
skip_tags: true
image: Visual Studio 2017
shallow_clone: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: qgIIfE76i59qTVO64mT7QwKcAUUYCQLie4XdUdlnt7MXLhrwqTbcfGUsCss/TmLg
cache: packages -> **\packages.config
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    .\Build\get-nuget.ps1

    .\fake.bat
test:
  assemblies:
    only:
    - _Binaries\AltCover.Tests\Debug+AnyCPU\*.Tests.dll
    - _Binaries\AltCover.Runner.Tests\Debug+AnyCPU\*.Tests.dll
    - _Binaries\AltCover.Shadow.Tests\Debug+AnyCPU\*.Tests.dll
artifacts:
- path: _Packaging\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: xkwBh+Yq1rXo/MzI5CdoGrLO8a3h73c3BaOFLQSgzE+uulMhOHYeHdPHXGWd9vRA
  on:
    branch: /release.*/
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: fR1kSlwEcdI9M2yyPlwK44QlFCOOpTU52ysj/hgcGxTMxNDtCW21zNeF4+o0fFtf
  on:
    branch: /releasechoco/.*/
notifications:
- provider: Slack
  incoming_webhook: 
    secure: yzKiNN5snmI7Vzh12NWUEKC+V/w5wGI1ZMUGPT8p5WRefjAbB6DSgYkmWnzNADq9SurhbgIE2hlcCQivCQJ5gQE3AEGFpe+V7Dh/Up/jV0U=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false